@startuml

title __V1's Class Diagram__\n

  namespace com.itbird.design {
    namespace chaiin.upgrade.v1 {
      class com.itbird.design.chaiin.upgrade.v1.ASystemUpgradeRequestHandler {
          ~ handleUpgradeRequest()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace chaiin.upgrade.v1 {
      class com.itbird.design.chaiin.upgrade.v1.BSystemUpgradeRequestHandler {
          ~ handleUpgradeRequest()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace chaiin.upgrade.v1 {
      class com.itbird.design.chaiin.upgrade.v1.CSystemUpgradeRequestHandler {
          ~ handleUpgradeRequest()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace chaiin.upgrade.v1 {
      class com.itbird.design.chaiin.upgrade.v1.InitUpgradeRequestHandler {
          ~ handleUpgradeRequest()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace chaiin.upgrade.v1 {
      interface com.itbird.design.chaiin.upgrade.v1.UpgradeErrorCode {
          {static} + ZIP_PACKAGE_PARSE_EROOR : int
      }
    }
  }
  

  namespace com.itbird.design {
    namespace chaiin.upgrade.v1 {
      class com.itbird.design.chaiin.upgrade.v1.UpgradeManager {
          {static} + getInstance()
          + startUpgrade()
          ~ UpgradeManager()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace chaiin.upgrade.v1 {
      class com.itbird.design.chaiin.upgrade.v1.UpgradeManager.UpgradeManagerHolder {
          {static} ~ mInstance : UpgradeManager
      }
    }
  }
  

  namespace com.itbird.design {
    namespace chaiin.upgrade.v1 {
      class com.itbird.design.chaiin.upgrade.v1.UpgradeRequest {
          ~ bSystemPath : String
          - aSystemPath : String
          - mcuPath : String
          - name : String
          - path : String
          + UpgradeRequest()
          + getMcuPath()
          + getName()
          + getPath()
          + getaSystemPath()
          + getbSystemPath()
          + setMcuPath()
          + setName()
          + setPath()
          + setaSystemPath()
          + setbSystemPath()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace chaiin.upgrade.v1 {
      abstract class com.itbird.design.chaiin.upgrade.v1.UpgradeRequestHandler {
          + TAG()
          + handlerRequest()
          + setNextHandler()
          {abstract} ~ handleUpgradeRequest()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace chaiin.upgrade.v1 {
      interface com.itbird.design.chaiin.upgrade.v1.UpgradeResultObservable {
          {abstract} + onError()
          {abstract} + onUpgradeProgressCallback()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace chaiin.upgrade.v1 {
      class com.itbird.design.chaiin.upgrade.v1.UpgradeResultObservableAdapter {
          + attatchUpgradeObserver()
          + detachUpgradeObserver()
          + onError()
          + onUpgradeProgressCallback()
      }
    }
  }
  

  com.itbird.design.chaiin.upgrade.v1.ASystemUpgradeRequestHandler -up-|> com.itbird.design.chaiin.upgrade.v1.UpgradeRequestHandler
  com.itbird.design.chaiin.upgrade.v1.BSystemUpgradeRequestHandler -up-|> com.itbird.design.chaiin.upgrade.v1.UpgradeRequestHandler
  com.itbird.design.chaiin.upgrade.v1.CSystemUpgradeRequestHandler -up-|> com.itbird.design.chaiin.upgrade.v1.UpgradeRequestHandler
  com.itbird.design.chaiin.upgrade.v1.InitUpgradeRequestHandler -up-|> com.itbird.design.chaiin.upgrade.v1.UpgradeRequestHandler
  com.itbird.design.chaiin.upgrade.v1.UpgradeManager o-- com.itbird.design.chaiin.upgrade.v1.UpgradeResultObservableAdapter : mAdapter
  com.itbird.design.chaiin.upgrade.v1.UpgradeManager +-down- com.itbird.design.chaiin.upgrade.v1.UpgradeManager.UpgradeManagerHolder
  com.itbird.design.chaiin.upgrade.v1.UpgradeRequestHandler o-- com.itbird.design.chaiin.upgrade.v1.UpgradeRequestHandler : nextHandler
  com.itbird.design.chaiin.upgrade.v1.UpgradeResultObservableAdapter .up.|> com.itbird.design.chaiin.upgrade.v1.UpgradeResultObservable
  com.itbird.design.chaiin.upgrade.v1.UpgradeResultObservableAdapter -up-|> android.database.Observable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
