@startuml

title __MOBILE's Class Diagram__\n

  namespace com.itbird.design {
    namespace facade.mobile {
      class com.itbird.design.facade.mobile.Camera {
          + takePhoto()
          + takeVideo()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace facade.mobile {
      interface com.itbird.design.facade.mobile.ICamera {
          {abstract} + takePhoto()
          {abstract} + takeVideo()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace facade.mobile {
      interface com.itbird.design.facade.mobile.IMusic {
          {abstract} + pause()
          {abstract} + play()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace facade.mobile {
      interface com.itbird.design.facade.mobile.Iphone {
          {abstract} + call()
          {abstract} + unCall()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace facade.mobile {
      class com.itbird.design.facade.mobile.Mobile {
          + Mobile()
          + callPhone()
          + takePhoto()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace facade.mobile {
      class com.itbird.design.facade.mobile.Music {
          + pause()
          + play()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace facade.mobile {
      class com.itbird.design.facade.mobile.Phone {
          + call()
          + unCall()
      }
    }
  }
  

  com.itbird.design.facade.mobile.Camera .up.|> com.itbird.design.facade.mobile.ICamera
  com.itbird.design.facade.mobile.Mobile o-- com.itbird.design.facade.mobile.ICamera : camera
  com.itbird.design.facade.mobile.Mobile o-- com.itbird.design.facade.mobile.Iphone : iphone
  com.itbird.design.facade.mobile.Mobile o-- com.itbird.design.facade.mobile.IMusic : music
  com.itbird.design.facade.mobile.Music .up.|> com.itbird.design.facade.mobile.IMusic
  com.itbird.design.facade.mobile.Phone .up.|> com.itbird.design.facade.mobile.Iphone


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
