@startuml

title __DEMO's Class Diagram__\n

  namespace com.itbird.design {
    namespace decorator {
      namespace demo {
        abstract class com.itbird.design.decorator.demo.Component {
            {abstract} + operation()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace decorator {
      namespace demo {
        class com.itbird.design.decorator.demo.ComponentImplA {
            {static} - TAG : String
            + ComponentImplA()
            + operation()
            - operationA()
            - operationB()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace decorator {
      namespace demo {
        class com.itbird.design.decorator.demo.ComponentImplB {
            {static} - TAG : String
            + ComponentImplB()
            + operation()
            - operationA()
            - operationB()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace decorator {
      namespace demo {
        class com.itbird.design.decorator.demo.ConCreateComponent {
            {static} - TAG : String
            + operation()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace decorator {
      namespace demo {
        abstract class com.itbird.design.decorator.demo.DecoratorComponent {
            + DecoratorComponent()
            + operation()
        }
      }
    }
  }
  

  com.itbird.design.decorator.demo.ComponentImplA -up-|> com.itbird.design.decorator.demo.DecoratorComponent
  com.itbird.design.decorator.demo.ComponentImplB -up-|> com.itbird.design.decorator.demo.DecoratorComponent
  com.itbird.design.decorator.demo.ConCreateComponent -up-|> com.itbird.design.decorator.demo.Component
  com.itbird.design.decorator.demo.DecoratorComponent -up-|> com.itbird.design.decorator.demo.Component
  com.itbird.design.decorator.demo.DecoratorComponent o-- com.itbird.design.decorator.demo.Component : component


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
