@startuml

title __V5's Class Diagram__\n

  namespace com.itbird.design {
    namespace factory {
      namespace imageLoader.v5 {
        class com.itbird.design.factory.imageLoader.v5.GlideImageLoader {
            + setImageView()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace factory {
      namespace imageLoader.v5 {
        interface com.itbird.design.factory.imageLoader.v5.IImageFactroy {
            {abstract} + getImageLoader()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace factory {
      namespace imageLoader.v5 {
        interface com.itbird.design.factory.imageLoader.v5.ILoadImage {
            {abstract} + setImageView()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace factory {
      namespace imageLoader.v5 {
        class com.itbird.design.factory.imageLoader.v5.ImageLoaderFactory {
            + getImageLoader()
            {static} + getInstance()
            - ImageLoaderFactory()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace factory {
      namespace imageLoader.v5 {
        class com.itbird.design.factory.imageLoader.v5.ImageLoaderFactory.ImageLoaderFactoryHolder {
            {static} ~ instance : ImageLoaderFactory
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace factory {
      namespace imageLoader.v5 {
        class com.itbird.design.factory.imageLoader.v5.PicassoImageLoader {
            + setImageView()
        }
      }
    }
  }
  

  com.itbird.design.factory.imageLoader.v5.GlideImageLoader .up.|> com.itbird.design.factory.imageLoader.v5.ILoadImage
  com.itbird.design.factory.imageLoader.v5.ImageLoaderFactory .up.|> com.itbird.design.factory.imageLoader.v5.IImageFactroy
  com.itbird.design.factory.imageLoader.v5.ImageLoaderFactory +-down- com.itbird.design.factory.imageLoader.v5.ImageLoaderFactory.ImageLoaderFactoryHolder
  com.itbird.design.factory.imageLoader.v5.PicassoImageLoader .up.|> com.itbird.design.factory.imageLoader.v5.ILoadImage


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
