@startuml

title __SOURCE's Class Diagram__\n

  namespace com.itbird.design {
    namespace adapter {
      namespace listview.source {
        interface com.itbird.design.adapter.listview.source.Adapter {
            {static} + IGNORE_ITEM_VIEW_TYPE : int
            {static} + NO_SELECTION : int
            + getAutofillOptions()
            {abstract} + getCount()
            {abstract} + getItem()
            {abstract} + getItemId()
            {abstract} + getItemViewType()
            {abstract} + getView()
            {abstract} + getViewTypeCount()
            {abstract} + hasStableIds()
            {abstract} + isEmpty()
            {abstract} + registerDataSetObserver()
            {abstract} + unregisterDataSetObserver()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace adapter {
      namespace listview.source {
        abstract class com.itbird.design.adapter.listview.source.BaseAdapter {
            - mAutofillOptions : CharSequence[]
            - mDataSetObservable : DataSetObservable
            + areAllItemsEnabled()
            + getAutofillOptions()
            + getDropDownView()
            + getItemViewType()
            + getViewTypeCount()
            + hasStableIds()
            + isEmpty()
            + isEnabled()
            + notifyDataSetChanged()
            + notifyDataSetInvalidated()
            + registerDataSetObserver()
            + unregisterDataSetObserver()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace adapter {
      namespace listview.source {
        interface com.itbird.design.adapter.listview.source.ListAdapter {
            {abstract} + areAllItemsEnabled()
            {abstract} + isEnabled()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace adapter {
      namespace listview.source {
        class com.itbird.design.adapter.listview.source.ListView {
            + setAdapter()
        }
      }
    }
  }
  
  com.itbird.design.adapter.listview.source.ListAdapter -up|>  com.itbird.design.adapter.listview.source.Adapter
  com.itbird.design.adapter.listview.source.BaseAdapter .up.|> com.itbird.design.adapter.listview.source.ListAdapter
  com.itbird.design.adapter.listview.source.ListView o-- com.itbird.design.adapter.listview.source.ListAdapter : adapter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
