@startuml

title __CLASSIMPL's Class Diagram__\n

  namespace com.itbird.design {
    namespace adapter {
      namespace classimpl {
        class com.itbird.design.adapter.classimpl.Client {
            + test()
            + test1()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace adapter {
      namespace classimpl {
        class com.itbird.design.adapter.classimpl.UpgradeModem {
            ~ upgradeObserverList : List<UpgradeObserver>
            + attachObserver()
            + detachObserver()
            {static} + getInstance()
            + startUpgrade()
            - UpgradeModem()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace adapter {
      namespace classimpl {
        class com.itbird.design.adapter.classimpl.UpgradeModem.UpgradeModemHolder {
            {static} - mInstance : UpgradeModem
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace adapter {
      namespace classimpl {
        interface com.itbird.design.adapter.classimpl.UpgradeObserver {
            {abstract} + upgradeA()
            {abstract} + upgradeB()
            {abstract} + upgradeC()
            {abstract} + upgradeD()
            {abstract} + upgradeE()
            {abstract} + upgradeF()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace adapter {
      namespace classimpl {
        abstract class com.itbird.design.adapter.classimpl.UpgradeObserverAdapter {
            + upgradeA()
            + upgradeB()
            + upgradeC()
            + upgradeD()
            + upgradeE()
            + upgradeF()
        }
      }
    }
  }
  

  com.itbird.design.adapter.classimpl.UpgradeModem +-down- com.itbird.design.adapter.classimpl.UpgradeModem.UpgradeModemHolder
  com.itbird.design.adapter.classimpl.UpgradeObserverAdapter .up.|> com.itbird.design.adapter.classimpl.UpgradeObserver


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
