@startuml

title __STATICC's Class Diagram__\n

  namespace com.itbird.design {
    namespace proxy {
      namespace demo.staticc {
        class com.itbird.design.proxy.demo.staticc.Client {
            + main()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace proxy {
      namespace demo.staticc {
        interface com.itbird.design.proxy.demo.staticc.IObject {
            {abstract} + methodA()
            {abstract} + methodB()
            {abstract} + methodC()
            {abstract} + methodD()
            {abstract} + methodE()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace proxy {
      namespace demo.staticc {
        class com.itbird.design.proxy.demo.staticc.ProxyObject {
            + ProxyObject()
            + methodA()
            + methodB()
            + methodC()
            + methodD()
            + methodE()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace proxy {
      namespace demo.staticc {
        class com.itbird.design.proxy.demo.staticc.SourceObject {
            + methodA()
            + methodB()
            + methodC()
            + methodD()
            + methodE()
        }
      }
    }
  }
  

  com.itbird.design.proxy.demo.staticc.ProxyObject .up.|> com.itbird.design.proxy.demo.staticc.IObject
  com.itbird.design.proxy.demo.staticc.ProxyObject o-- com.itbird.design.proxy.demo.staticc.IObject : mSourceObject
  com.itbird.design.proxy.demo.staticc.SourceObject .up.|> com.itbird.design.proxy.demo.staticc.IObject


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
