@startuml

title __DIALOG's Class Diagram__\n

  namespace com.itbird.design {
    namespace builder.dialog {
      class com.itbird.design.builder.dialog.CommonDialog {
          {static} - DIALOG_STYLE_HIGH : int
          {static} - DIALOG_STYLE_NORMAL : int
          {static} - DIALOG_STYLE_SMALL : int
          - dialogStyle : int
          - mButtonHandler : OnClickListener
          - messageTextView : TextView
          - negativeButton : Button
          - negativeMessage : Message
          - positiveButton : Button
          - positiveMessage : Message
          - rootView : View
          - titleTextView : TextView
          + CommonDialog()
          + CommonDialog()
          + setMessage()
          + setNegativeButton()
          + setPositiveButton()
          + setTitle()
          # CommonDialog()
          ~ CommonDialog()
          - getInflateLayout()
          - setWindowStyle()
          - setupView()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace builder.dialog {
      class com.itbird.design.builder.dialog.CommonDialog.Builder {
          - cancelable : boolean
          - context : Context
          - message : String
          - negativeOnCLickListener : OnClickListener
          - negativeText : String
          - onCancelListener : OnCancelListener
          - onDismissListener : OnDismissListener
          - onKeyListener : OnKeyListener
          - positiveOnClickListener : OnClickListener
          - positiveText : String
          - title : String
          + Builder()
          + create()
          + setCancelable()
          + setMessage()
          + setMessage()
          + setNegativeButton()
          + setNegativeButton()
          + setOnCancelListener()
          + setOnDismissListener()
          + setOnKeyListener()
          + setPositiveButton()
          + setPositiveButton()
          + setTitle()
          + setTitle()
          + show()
          - apply()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace builder.dialog {
      class com.itbird.design.builder.dialog.CommonDialog.ButtonHandler {
          {static} - MSG_DISMISS_DIALOG : int
          - mDialog : WeakReference<DialogInterface>
          + ButtonHandler()
          + handleMessage()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace builder.dialog {
      class com.itbird.design.builder.dialog.CommonProgressDialog {
          {static} + STYLE_HORIZONTAL : int
          {static} + STYLE_SPINNER : int
          - mHasStarted : boolean
          - mMax : int
          - mMessage : CharSequence
          - mMessageView : TextView
          - mProgress : ProgressBar
          - mProgressPercent : TextView
          - mProgressPercentFormat : NumberFormat
          - mProgressStyle : int
          - mProgressVal : int
          - mTitle : CharSequence
          - mTitleView : TextView
          - mViewUpdateHandler : Handler
          + CommonProgressDialog()
          + CommonProgressDialog()
          + getMax()
          + getProgress()
          + onStart()
          + setMax()
          + setMessage()
          + setProgress()
          + setProgressPercentFormat()
          + setProgressStyle()
          + setTitle()
          {static} + show()
          {static} + show()
          {static} + show()
          # onCreate()
          # onStop()
          - initFormats()
          - onProgressChanged()
          - setWindowStyle()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace builder.dialog {
      abstract class com.itbird.design.builder.dialog.CustomCountDownTimer {
          {static} - MSG : int
          - isPause : boolean
          - isStop : boolean
          - mCountdownInterval : long
          - mHandler : Handler
          - mMillisInFuture : long
          - mPauseTimeInFuture : long
          - mStopTimeInFuture : long
          + CustomCountDownTimer()
          {abstract} + onFinish()
          {abstract} + onTick()
          + pause()
          + restart()
          + start()
          + stop()
          - start()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace builder.dialog {
      class com.itbird.design.builder.dialog.CustomCountDownTimerDialog {
          + CustomCountDownTimerDialog()
          + CustomCountDownTimerDialog()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace builder.dialog {
      class com.itbird.design.builder.dialog.CustomCountDownTimerDialog.Builder {
          - context : Context
          - title : String
          + Builder()
          + create()
          + setCountDownTimerFinsh()
          + setTitle()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace builder.dialog {
      interface com.itbird.design.builder.dialog.CustomCountDownTimerDialog.CountDownTimerFinsh {
          {abstract} + onFinish()
      }
    }
  }
  

  com.itbird.design.builder.dialog.CommonDialog .up.|> android.content.DialogInterface
  com.itbird.design.builder.dialog.CommonDialog -up-|> android.app.Dialog
  com.itbird.design.builder.dialog.CommonDialog o-- com.itbird.design.builder.dialog.CommonDialog.ButtonHandler : handler
  com.itbird.design.builder.dialog.CommonDialog +-down- com.itbird.design.builder.dialog.CommonDialog.Builder
  com.itbird.design.builder.dialog.CommonDialog +-down- com.itbird.design.builder.dialog.CommonDialog.ButtonHandler
  com.itbird.design.builder.dialog.CommonDialog.ButtonHandler -up-|> android.os.Handler
  com.itbird.design.builder.dialog.CommonProgressDialog -up-|> android.app.Dialog
  com.itbird.design.builder.dialog.CustomCountDownTimerDialog -up-|> android.app.Dialog
  com.itbird.design.builder.dialog.CustomCountDownTimerDialog +-down- com.itbird.design.builder.dialog.CustomCountDownTimerDialog.Builder
  com.itbird.design.builder.dialog.CustomCountDownTimerDialog +-down- com.itbird.design.builder.dialog.CustomCountDownTimerDialog.CountDownTimerFinsh
  com.itbird.design.builder.dialog.CustomCountDownTimerDialog.Builder o-- com.itbird.design.builder.dialog.CustomCountDownTimerDialog.CountDownTimerFinsh : mCountDownTimerFinsh


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
