@startuml

title __DEMO's Class Diagram__\n

  namespace com.itbird.design {
    namespace iterator {
      namespace demo {
        interface com.itbird.design.iterator.demo.BaseSystem {
            {abstract} + getIterator()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace iterator {
      namespace demo {
        class com.itbird.design.iterator.demo.Userinfo {
            ~ age : int
            ~ name : String
            + Userinfo()
            + getAge()
            + getName()
            + setAge()
            + setName()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace iterator {
      namespace demo {
        class com.itbird.design.iterator.demo.UserinfoSystemA {
            ~ userinfoIterator : ListIterator<Userinfo>
            ~ userinfos : List<Userinfo>
            + UserinfoSystemA()
            + getIterator()
            + getUserinfos()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace iterator {
      namespace demo {
        class com.itbird.design.iterator.demo.UserinfoSystemB {
            ~ userinfoIterator : ArrayIterator<Userinfo>
            ~ userinfos : Userinfo[]
            + UserinfoSystemB()
            + getIterator()
            + getUserinfos()
        }
      }
    }
  }
  

  com.itbird.design.iterator.demo.UserinfoSystemA .up.|> com.itbird.design.iterator.demo.BaseSystem
  com.itbird.design.iterator.demo.UserinfoSystemB .up.|> com.itbird.design.iterator.demo.BaseSystem


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
