@startuml

title __V2's Class Diagram__\n

  namespace com.itbird.design {
    namespace strategy {
      namespace demo.compute.v2 {
        class com.itbird.design.strategy.demo.compute.v2.ComputeADD {
            + compute()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace strategy {
      namespace demo.compute.v2 {
        class com.itbird.design.strategy.demo.compute.v2.ComputeDel {
            + compute()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace strategy {
      namespace demo.compute.v2 {
        class com.itbird.design.strategy.demo.compute.v2.ComputeDiv {
            + compute()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace strategy {
      namespace demo.compute.v2 {
        class com.itbird.design.strategy.demo.compute.v2.ComputeMul {
            + compute()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace strategy {
      namespace demo.compute.v2 {
        class com.itbird.design.strategy.demo.compute.v2.Context {
            ~ iCompute : ICompute<Double>
            + Context()
            + compute()
        }
      }
    }
  }
  

  namespace com.itbird.design {
    namespace strategy {
      namespace demo.compute.v2 {
        interface com.itbird.design.strategy.demo.compute.v2.ICompute {
            {abstract} + compute()
        }
      }
    }
  }
  

  com.itbird.design.strategy.demo.compute.v2.ComputeADD .up.|> com.itbird.design.strategy.demo.compute.v2.ICompute
  com.itbird.design.strategy.demo.compute.v2.ComputeDel .up.|> com.itbird.design.strategy.demo.compute.v2.ICompute
  com.itbird.design.strategy.demo.compute.v2.ComputeDiv .up.|> com.itbird.design.strategy.demo.compute.v2.ICompute
  com.itbird.design.strategy.demo.compute.v2.ComputeMul .up.|> com.itbird.design.strategy.demo.compute.v2.ICompute


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
