@startuml

title __V1's Class Diagram__\n

  namespace com.itbird.design {
    namespace factory.demo.v1 {
      class com.itbird.design.factory.demo.v1.ConCreteIProductA {
          {static} - TAG : String
          + function()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace factory.demo.v1 {
      class com.itbird.design.factory.demo.v1.ConCreteIProductB {
          {static} - TAG : String
          + function()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace factory.demo.v1 {
      class com.itbird.design.factory.demo.v1.ConCreteIProductC {
          {static} - TAG : String
          + function()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace factory.demo.v1 {
      class com.itbird.design.factory.demo.v1.ConcreteFactory {
          + createProduct()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace factory.demo.v1 {
      interface com.itbird.design.factory.demo.v1.IFactroy {
          {abstract} + createProduct()
      }
    }
  }
  

  namespace com.itbird.design {
    namespace factory.demo.v1 {
      interface com.itbird.design.factory.demo.v1.IProduct {
          {abstract} + function()
      }
    }
  }
  

  com.itbird.design.factory.demo.v1.ConCreteIProductA .up.|> com.itbird.design.factory.demo.v1.IProduct
  com.itbird.design.factory.demo.v1.ConCreteIProductB .up.|> com.itbird.design.factory.demo.v1.IProduct
  com.itbird.design.factory.demo.v1.ConCreteIProductC .up.|> com.itbird.design.factory.demo.v1.IProduct
  com.itbird.design.factory.demo.v1.ConcreteFactory .up.|> com.itbird.design.factory.demo.v1.IFactroy


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
